api_keys:
  slack: "$SLACK_TOKEN"
  pagerduty:
    org: "$PAGERDUTY_ORG"
    key: "$PAGERDUTY_KEY"

groups:
  - name: devops-help
    schedules:
      - PCLYMC8
  - name: data-help
    schedules:
      - PCLYMC8
  - name: it-help
    schedules:
      - PBC8G5I
  - name: eng-help
    schedules:
      - P61VATU
  - name: eng-help-backup
    schedules:
      - P8MOV3F
